# Generated by Django 5.1.7 on 2025-05-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_imagenservicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion_breve',
            field=models.TextField(blank=True, null=True),
        ),
    ]
