# Generated by Django 5.0.6 on 2025-05-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_servicio_descripcion_breve'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
