# Generated by Django 5.1.7 on 2025-05-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_trabajador_latitud_trabajador_longitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
